title: Koushik Vikram
author: Koushik Vikram
description: "Engineer, reader, interested in many things"

favicon: "assets/favicon_poimandres.png"
remote_theme: riggraz/no-style-please

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

theme_config:
  appearance: "dark"
  show_description: true
  back_home_text: ".."
  date_format: "%Y-%m-%d"
